version: "3.9"
services:
  webapp:
    build: .
    ports:
      - "7500:8000"
    environment:
      IS_DOCKER: "True"
    depends_on:
      - database
  database:
    image: postgres:15-alpine
    volumes:
      - mydata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: multishop_db
volumes:
  mydata: 