# Generated by Django 4.2.2 on 2023-08-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_resetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
