# Generated by Django 4.2.2 on 2023-08-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='used_coupon',
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('azerbaijan', 'Azerbaijan'), ('russia', 'Russia'), ('turkey', 'Turkey'), ('usa', 'USA')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.IntegerField(default=0),
        ),
    ]
