# Generated by Django 4.2.2 on 2023-08-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_order_used_coupon_order_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
