# Generated by Django 4.2.2 on 2023-07-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_uptade_product_update_product_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='general',
            field=models.ManyToManyField(related_name='products', to='shop.generalcategory'),
        ),
    ]
