# Generated by Django 4.2.2 on 2023-08-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update',
            new_name='updated',
        ),
    ]
